// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TuristickaAgencija.Mvc.Data;

#nullable disable

namespace TuristickaAgencija.Mvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619144027_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("TuristickaAgencija.Mvc.Models.Aranzman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojDana")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cijena")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumPolaska")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumPovratka")
                        .HasColumnType("TEXT");

                    b.Property<int>("DestinacijaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DestinacijaId");

                    b.ToTable("Aranzmani");
                });

            modelBuilder.Entity("TuristickaAgencija.Mvc.Models.Destinacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Drzava")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Popularna")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Destinacije");
                });

            modelBuilder.Entity("TuristickaAgencija.Mvc.Models.Aranzman", b =>
                {
                    b.HasOne("TuristickaAgencija.Mvc.Models.Destinacija", "Destinacija")
                        .WithMany("Aranzmani")
                        .HasForeignKey("DestinacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destinacija");
                });

            modelBuilder.Entity("TuristickaAgencija.Mvc.Models.Destinacija", b =>
                {
                    b.Navigation("Aranzmani");
                });
#pragma warning restore 612, 618
        }
    }
}
